apiVersion: v1
kind: Service
metadata:
    name: twebapp
spec:
    type: LoadBalancer
    ports:
    - port: 30005
      targetPort: 8080
      nodePort: 30005
    selector:
        app: twebapp